### ISSUE TITLE
Readme.md example not working

### ISSUE THREAD

**Issue by KerryXEX** [Gamefound/PostHog.NET#1]
Dear Team,

the example setup with "empty" server confg as described is not working (at least not for EU accounts).
The server config has to be set to 
`config.Host = "eu.posthog.com";`

otherwise no connection is made.

Cheers
Kerry.

**Comment by gregleongf** [comment]
Thanks for the info. I've actually removed the comment about leaving the value empty because this package was created to work with self-hosted versions of PostHog. It is not officially supported by PostHog and may not be compatible with the latest version of PostHog Cloud.
